mutation USER_SIGNUP($address: String!) {
  signup(params: { address: $address }) {
    jwt
    refreshToken
  }
}

query USER_LOGIN($address: String!) {
  signin(params: { address: $address }) {
    jwt
    refreshToken
  }
}

mutation USER_SIGNOUT {
  signout {
    ok
  }
}

query USER_REFRESH_TOKEN($refreshToken: String!, $fingerprintHash: String!) {
  refreshJwtToken(
    refreshToken: $refreshToken
    fingerprintHash: $fingerprintHash
  ) {
    jwt
  }
}

query USER_CHECK_ADDRESS($address: String!) {
  user(where: { address: { _eq: $address } }) {
    id
  }
}

mutation USER_INSERT_ONE($user: user_insert_input!) {
  insert_user_one(object: $user) {
    id
  }
}

query HASURA_ME {
  user {
    id
    address
    chainId
    refresh_token
    refresh_token_expires_at
  }
}
