name: Deploy Vercel Lambda
on:
  pull_request:
    paths:
      - 'lambda/user'
  push:
    branches:
      - master
    paths:
      - 'lambda/user'

  workflow_dispatch:

env:
  LAMBDA_PATH: 'lambda/user'

jobs:
  vercel-lambda-checks:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v2

      - name: 🏗 Setup Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
 
      - name: 📦 Build
        run: |
          yarn install --frozen-lockfile
        shell: bash
        working-directory: $LAMBDA_PATH

      # - name: 🚀 Deploy to Vercel Prod
      #   id: deploy-vercel-production
      #   uses: amondnet/vercel-action@v20
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
      #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
      #     vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
      #     vercel-args: '--prod' 
      #     scope: ${{ secrets.VERCEL_ORG_ID }}
      #     working-directory: ./lambda/user

      # - name: 💬 Comment pr
      #   uses: phulsechinmay/rewritable-pr-comment@v0.3.0
      #   if: ${{ steps.deploy-vercel-production.outputs.DEPLOYMENT_CREATED }}
      #   with:
      #     message: |
      #       This pull request has been deployed to Vercel.

      #       <table>
      #         <tr>
      #           <td><strong>✅ Preview:</strong></td>
      #           <td><a href='${{ steps.deploy-vercel-production.outputs.PREVIEW_URL }}'>${{ steps.deploy-vercel-production.outputs.PREVIEW_URL }}</a></td>
      #         </tr>
      #         <tr>
      #           <td><strong>🔍 Inspect:</strong></td>
      #           <td><a href='${ steps.deploy-vercel-production.outputs.DEPLOYMENT_INSPECTOR_URL }'>${ steps.deploy-vercel-production.outputs.DEPLOYMENT_INSPECTOR_URL }</a></td>
      #         </tr>
      #       </table>

      #       [View Workflow Logs](${ LOG_URL })
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     COMMENT_IDENTIFIER: 'vercel-deploy'

      # - name: Run Tests Against Vercel
      #   env:
      #     VERCEL_URL: ${{ steps.deploy-vercel-staging.outputs.preview-url }}
      #   run: npm run test
 
      # - name: Deploy to Production
      #   uses: amondnet/vercel-action@v20
      #   id: deploy-vercel-production
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
      #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
      #     vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_TL_ENGINE }}
      #     vercel-args: '--prod'
      #     scope: ${{ secrets.VERCEL_ORG_ID }}